# Generated by Django 4.1.5 on 2023-01-28 19:35

from django.db import migrations, models
import django.utils.timezone
import django_quill.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=265)),
                ('acbs_category', models.PositiveIntegerField(blank=True, choices=[(1, 'Snooker'), (2, 'Billiards'), (3, '10Red'), (4, '6Red'), (5, 'Team'), (6, 'Juniors'), (7, '8Ball Pool'), (8, '9Ball Pool'), (9, '10Ball Pool'), (10, 'World Cup')], null=True)),
                ('location', models.CharField(blank=True, max_length=200, null=True)),
                ('venue', models.CharField(blank=True, max_length=200, null=True)),
                ('start_date', models.DateField(default=django.utils.timezone.now)),
                ('end_date', models.DateField(default=django.utils.timezone.now)),
                ('results', models.URLField(blank=True, null=True)),
                ('photographs', models.URLField(blank=True, null=True)),
                ('video', models.URLField(blank=True, null=True)),
                ('live', models.URLField(blank=True, null=True)),
                ('content1', django_quill.fields.QuillField(blank=True)),
                ('content2', django_quill.fields.QuillField(blank=True)),
                ('slug', models.CharField(blank=True, max_length=256, null=True)),
                ('year', models.CharField(blank=True, max_length=4, null=True)),
            ],
        ),
    ]
