# Generated by Django 4.1.5 on 2023-02-28 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='event_banner',
            field=models.ImageField(blank=True, null=True, upload_to='news/images'),
        ),
    ]
