# Generated by Django 4.1.5 on 2023-04-30 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_alter_event_acbs_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='acbs_category',
            field=models.CharField(blank=True, choices=[('Snooker', 'Snooker'), ('Billiards', 'Billiards'), ('10Red', '10Red'), ('6Red', '6Red'), ('Team', 'Team'), ('Juniors', 'Juniors'), ('8Ball Pool', '8Ball Pool'), ('9Ball Pool', '9Ball Pool'), ('10Ball Pool', '10Ball Pool'), ('World Cup', 'World Cup')], max_length=100, null=True),
        ),
    ]
