# Generated by Django 4.1.5 on 2023-05-06 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_event_is_featured'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='groups',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='knockouts',
            field=models.URLField(blank=True, null=True),
        ),
    ]
