# Generated by Django 4.1.5 on 2023-01-20 11:07

from django.db import migrations
import django_quill.fields


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_alter_news_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='content',
            field=django_quill.fields.QuillField(blank=True),
        ),
    ]
