# Generated by Django 4.1.5 on 2023-01-20 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_alter_news_content'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='acbs_category',
        ),
        migrations.AlterField(
            model_name='news',
            name='category',
            field=models.PositiveIntegerField(choices=[('latest', 'LATEST'), ('featured', 'FEATURED')]),
        ),
    ]
