# Generated by Django 4.1.5 on 2023-01-20 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_remove_news_acbs_category_alter_news_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='acbs_category',
            field=models.PositiveIntegerField(blank=True, choices=[(1, 'World Snooker'), (2, 'World Billiards'), (3, 'World 6Reds'), (4, 'World Team'), (5, 'World U21'), (6, 'World U18'), (7, 'World U17'), (8, 'World U16'), (9, 'World Cup')], null=True),
        ),
        migrations.AlterField(
            model_name='news',
            name='category',
            field=models.PositiveIntegerField(choices=[(1, 'LATEST'), (2, 'FEATURED')]),
        ),
    ]
