# Generated by Django 4.1.5 on 2023-04-23 12:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0007_newswriter_news_writer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='newswriter',
            old_name='titel',
            new_name='title',
        ),
    ]
