# Generated by Django 4.1.5 on 2023-04-30 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0008_rename_titel_newswriter_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='acbs_category',
            field=models.PositiveIntegerField(blank=True, choices=[('Snooker', 'Snooker'), ('Billiards', 'Billiards'), ('10Red', '10Red'), ('6Red', '6Red'), ('Team', 'Team'), ('Juniors', 'Juniors'), ('8Ball Pool', '8Ball Pool'), ('9Ball Pool', '9Ball Pool'), ('10Ball Pool', '10Ball Pool'), ('World Cup', 'World Cup')], null=True),
        ),
    ]
