# Generated by Django 4.1.5 on 2023-01-21 05:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Annoucements',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('image', models.ImageField(blank=True, null=True, upload_to='announcements/images')),
                ('url', models.URLField(blank=True, null=True)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('bool', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=datetime.datetime(2023, 1, 21, 5, 46, 15, 31739, tzinfo=datetime.timezone.utc))),
            ],
            options={
                'verbose_name': 'Annoucements',
                'verbose_name_plural': 'Annoucements',
            },
        ),
    ]
