# Generated by Django 4.1.5 on 2023-01-21 06:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_annoucement_delete_annoucements'),
    ]

    operations = [
        migrations.RenameField(
            model_name='annoucement',
            old_name='bool',
            new_name='show',
        ),
        migrations.AlterField(
            model_name='annoucement',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 21, 6, 31, 16, 308082, tzinfo=datetime.timezone.utc)),
        ),
    ]
