# Generated by Django 4.1.5 on 2023-01-21 06:57

import datetime
from django.db import migrations, models
import django_quill.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_rename_bool_annoucement_show_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', django_quill.fields.QuillField(blank=True)),
            ],
            options={
                'verbose_name': 'About Us',
                'verbose_name_plural': 'About Us',
            },
        ),
        migrations.AlterField(
            model_name='annoucement',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 21, 6, 57, 53, 976708, tzinfo=datetime.timezone.utc)),
        ),
    ]
