# Generated by Django 4.1.5 on 2023-01-28 19:36

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_alter_annoucement_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='annoucement',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
