# Generated by Django 4.1.5 on 2023-03-02 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_alter_annoucement_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='Executive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=200)),
                ('origin_country', models.CharField(max_length=100, verbose_name='Country of Origin')),
            ],
        ),
        migrations.CreateModel(
            name='MemberCountries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('flag', models.ImageField(upload_to='countries/flags')),
                ('facebook', models.URLField(blank=True, null=True)),
                ('instagram', models.URLField(blank=True, null=True)),
                ('twitter', models.URLField(blank=True, null=True)),
                ('site', models.URLField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Member Country',
                'verbose_name_plural': 'Member Countries',
            },
        ),
    ]
