# Generated by Django 4.1.5 on 2023-03-02 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_executive_membercountries'),
    ]

    operations = [
        migrations.AddField(
            model_name='executive',
            name='image',
            field=models.ImageField(default='', upload_to='executives'),
            preserve_default=False,
        ),
    ]
