# Generated by Django 4.1.5 on 2023-05-16 17:23

from django.db import migrations
import django_quill.fields


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0011_contact_download_pastchampion_rule"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="rule",
            options={"verbose_name": "Rule", "verbose_name_plural": "Rules"},
        ),
        migrations.AlterField(
            model_name="pastchampion",
            name="content",
            field=django_quill.fields.QuillField(blank=True),
        ),
    ]
