# Generated by Django 4.1.5 on 2023-08-01 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0012_alter_rule_options_alter_pastchampion_content"),
    ]

    operations = [
        migrations.RenameField(
            model_name="membercountries",
            old_name="president",
            new_name="person1",
        ),
        migrations.AddField(
            model_name="membercountries",
            name="person2",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="membercountries",
            name="position1",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="membercountries",
            name="position2",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
